framework:
    cache:
        app: cache.adapter.redis_tag_aware
        default_redis_provider: 'redis://cache:6379'
    trusted_proxies: '%env(TRUSTED_PROXIES)%'
    trusted_headers: [ 'x-forwarded-for', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-host' ]